flags: {}
user-message: ! 'Warning (added by new or init): Specified resolver could not satisfy
  all dependencies. Some external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- '.'
extra-deps:
- monad-gen-0.3.0.1
- monad-supply-0.6
resolver: lts-6.3
